"""depot temporaire des imports en base (disque ephemere)

Revision ID: 1f9d5e5e3567
Revises: 51c4431ae16e
Create Date: 2026-07-29 15:10:12.339908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f9d5e5e3567'
down_revision = '51c4431ae16e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_temporaire',
    sa.Column('id_import_temporaire', sa.Integer(), nullable=False),
    sa.Column('jeton', sa.String(length=64), nullable=False),
    sa.Column('nom_fichier', sa.String(length=255), nullable=False),
    sa.Column('contenu', sa.LargeBinary(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('date_depot', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id_utilisateur'], ),
    sa.PrimaryKeyConstraint('id_import_temporaire')
    )
    with op.batch_alter_table('import_temporaire', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_temporaire_jeton'), ['jeton'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_temporaire', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_temporaire_jeton'))

    op.drop_table('import_temporaire')
    # ### end Alembic commands ###
