"""idempotence des imports (hash fichier + cle ligne + ignorees)

Revision ID: 51c4431ae16e
Revises: 7e82ed7716eb
Create Date: 2026-07-28 04:03:12.811683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c4431ae16e'
down_revision = '7e82ed7716eb'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('import_fichier', schema=None) as batch_op:
        # server_default='0' est indispensable : la table contient déjà des
        # lignes en production, et une colonne NOT NULL sans valeur par défaut
        # ferait échouer la migration sur PostgreSQL.
        batch_op.add_column(
            sa.Column('lignes_ignorees', sa.Integer(), nullable=False, server_default='0')
        )
        batch_op.add_column(sa.Column('hash_fichier', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_import_fichier_hash_fichier'), ['hash_fichier'], unique=False)

    with op.batch_alter_table('ligne_commande', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cle_idempotence', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_ligne_commande_cle_idempotence'), ['cle_idempotence'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ligne_commande', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ligne_commande_cle_idempotence'))
        batch_op.drop_column('cle_idempotence')

    with op.batch_alter_table('import_fichier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_fichier_hash_fichier'))
        batch_op.drop_column('hash_fichier')
        batch_op.drop_column('lignes_ignorees')

    # ### end Alembic commands ###
