"""ajout table vente (Pulse)

Revision ID: 7e82ed7716eb
Revises: 4b8012d89dd8
Create Date: 2026-07-15 21:37:49.993643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e82ed7716eb'
down_revision = '4b8012d89dd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vente',
    sa.Column('id_vente', sa.Integer(), nullable=False),
    sa.Column('commande_id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mode_paiement', sa.String(length=40), nullable=True),
    sa.Column('date_vente', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commande_id'], ['commande.id_commande'], ),
    sa.PrimaryKeyConstraint('id_vente')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vente')
    # ### end Alembic commands ###
